# Generated by Django 2.2 on 2019-04-08 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catalog', '0002_auto_20190408_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('years_to_create', models.DateField(default='1950', verbose_name='год издания')),
                ('count_sheets', models.PositiveSmallIntegerField(verbose_name='число страниц')),
                ('ISBN', models.SmallIntegerField(verbose_name='универсальный номер')),
                ('mass', models.SmallIntegerField(verbose_name='вес')),
                ('rating', models.SmallIntegerField(verbose_name='возраст')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='На складе')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to='Catalog.Authors', verbose_name='Авторство')),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='binding', to='Catalog.Binding', verbose_name='виды_переплета')),
                ('formate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formats', to='Catalog.Format', verbose_name='формат')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genres', to='Catalog.Genre', verbose_name='Жанры')),
                ('publish_house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publish', to='Catalog.Publishing_house', verbose_name='Издательства')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='Catalog.Serie', verbose_name='Серия')),
            ],
            options={
                'ordering': ['name'],
                'index_together': {('id', 'description')},
            },
        ),
    ]
