# Generated by Django 2.2 on 2019-04-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='binding',
            new_name='bindings',
        ),
    ]
