# Generated by Django 2.2 on 2019-04-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190409_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='books/pics/%Y/%m/%d/', verbose_name='Изображение товара'),
        ),
    ]
