# Generated by Django 2.2 on 2019-05-02 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190426_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'книга', 'verbose_name_plural': 'книги'},
        ),
        migrations.AlterIndexTogether(
            name='book',
            index_together=set(),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
