# Generated by Django 2.2 on 2019-04-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='Фамилия')),
                ('country', models.CharField(blank=True, max_length=20, null=True, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Тип переплета')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Переплет книги',
                'verbose_name_plural': 'Виды переплета',
                'ordering': ['binding'],
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Формат')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Формат книги',
                'verbose_name_plural': 'Виды форматов',
                'ordering': ['format'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название жанра')),
                ('description', models.CharField(db_index=True, max_length=300, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publishing_house',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название')),
                ('description', models.CharField(db_index=True, max_length=300, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Серия')),
                ('description', models.CharField(db_index=True, max_length=300, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
                'ordering': ['name'],
            },
        ),
    ]
