# Generated by Django 2.2 on 2019-04-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binding',
            name='bindings',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Тип переплета'),
        ),
    ]
