# Generated by Django 2.2 on 2019-04-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0002_auto_20190417_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Описание'),
        ),
    ]
